[2025-10-01T10:32:43.751+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-01T10:32:43.776+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main.run_pyspark_task manual__2025-10-01T10:32:42.649577+00:00 [queued]>
[2025-10-01T10:32:43.782+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main.run_pyspark_task manual__2025-10-01T10:32:42.649577+00:00 [queued]>
[2025-10-01T10:32:43.783+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-01T10:32:43.795+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_pyspark_task> on 2025-10-01 10:32:42.649577+00:00
[2025-10-01T10:32:43.801+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=64) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-01T10:32:43.802+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'main', 'run_pyspark_task', 'manual__2025-10-01T10:32:42.649577+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpa2zdarys']
[2025-10-01T10:32:43.803+0000] {standard_task_runner.py:63} INFO - Started process 65 to run task
[2025-10-01T10:32:43.803+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask run_pyspark_task
[2025-10-01T10:32:43.836+0000] {task_command.py:426} INFO - Running <TaskInstance: main.run_pyspark_task manual__2025-10-01T10:32:42.649577+00:00 [running]> on host 8f02716048bd
[2025-10-01T10:32:43.903+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main' AIRFLOW_CTX_TASK_ID='run_pyspark_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-01T10:32:42.649577+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-01T10:32:42.649577+00:00'
[2025-10-01T10:32:43.904+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-01T10:32:47.847+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-01T10:32:47.848+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main.py", line 30, in run_spark_job
    df = spark.read.csv("/opt/airflow/tmp/russian_houses.csv", header=True, schema=schema, delimiter=",")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataFrameReader.csv() got an unexpected keyword argument 'delimiter'
[2025-10-01T10:32:47.860+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=main, task_id=run_pyspark_task, run_id=manual__2025-10-01T10:32:42.649577+00:00, execution_date=20251001T103242, start_date=20251001T103243, end_date=20251001T103247
[2025-10-01T10:32:47.876+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task run_pyspark_task (DataFrameReader.csv() got an unexpected keyword argument 'delimiter'; 65)
[2025-10-01T10:32:47.914+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-01T10:32:47.931+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-01T10:32:47.935+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
