[2025-10-06T14:05:24.154+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-06T14:05:24.169+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main.run_pyspark_task manual__2025-10-06T14:05:22.989839+00:00 [queued]>
[2025-10-06T14:05:24.174+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main.run_pyspark_task manual__2025-10-06T14:05:22.989839+00:00 [queued]>
[2025-10-06T14:05:24.174+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-06T14:05:24.186+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_pyspark_task> on 2025-10-06 14:05:22.989839+00:00
[2025-10-06T14:05:24.193+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6703) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-06T14:05:24.195+0000] {standard_task_runner.py:63} INFO - Started process 6705 to run task
[2025-10-06T14:05:24.196+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'main', 'run_pyspark_task', 'manual__2025-10-06T14:05:22.989839+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpi4yyc5ez']
[2025-10-06T14:05:24.198+0000] {standard_task_runner.py:91} INFO - Job 147: Subtask run_pyspark_task
[2025-10-06T14:05:24.271+0000] {task_command.py:426} INFO - Running <TaskInstance: main.run_pyspark_task manual__2025-10-06T14:05:22.989839+00:00 [running]> on host 5adecdfd8c83
[2025-10-06T14:05:24.337+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main' AIRFLOW_CTX_TASK_ID='run_pyspark_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-06T14:05:22.989839+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-06T14:05:22.989839+00:00'
[2025-10-06T14:05:24.338+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-06T14:05:36.328+0000] {logging_mixin.py:188} INFO - +--------+------------------+------------------+----------------+--------+----------+-------------------+--------------------+--------------------+--------------------+-------------------+--------------------+
|house_id|          latitude|         longitude|maintenance_year|  square|population|             region|       locality_name|             address|        full_address|communal_service_id|         description|
+--------+------------------+------------------+----------------+--------+----------+-------------------+--------------------+--------------------+--------------------+-------------------+--------------------+
|       1|         44.707617|         43.006476|            1974|2 661.10|        89|Ставропольский край|село Александровское|с. Александровско...|Ставропольский кр...|                1.0|Жилой дом в , по ...|
|       2|44.706720000000004|         43.005281|            1989|3 111.10|       115|Ставропольский край|село Александровское|с. Александровско...|Ставропольский кр...|                1.0|Жилой дом в , по ...|
|       3|         44.708302|43.006665000000005|            1977|2 896.04|        89|Ставропольский край|село Александровское|с. Александровско...|Ставропольский кр...|                1.0|Жилой дом в , по ...|
|       5|44.711946999999995|          42.97358|            1978|1 061.92|        26|Ставропольский край|село Александровское|с. Александровско...|Ставропольский кр...|                1.0|Жилой дом в , по ...|
|       6|         44.707751|         43.005515|            1978|2 688.70|       105|Ставропольский край|село Александровское|с. Александровско...|Ставропольский кр...|                2.0|Жилой дом в , по ...|
|       7|44.711946999999995|          42.97358|            1973|  854.90|        40|Ставропольский край|село Александровское|с. Александровско...|Ставропольский кр...|                3.0|Жилой дом в , по ...|
|       8|44.723622999999996|         42.996864|            1978|  924.40|        31|Ставропольский край|село Александровское|с. Александровско...|Ставропольский кр...|                4.0|Жилой дом в , по ...|
|       9|44.721765999999995|          43.02013|            1974|1 011.30|        38|Ставропольский край|село Александровское|с. Александровско...|Ставропольский кр...|                5.0|Жилой дом в , по ...|
|      10|         44.710557|         43.000278|            1963|  621.21|        20|Ставропольский край|село Александровское|с. Александровско...|Ставропольский кр...|                6.0|Жилой дом в , по ...|
|      11|44.724903999999995|         43.003359|            1972|  681.60|        26|Ставропольский край|село Александровское|с. Александровско...|Ставропольский кр...|                7.0|Жилой дом в , по ...|
+--------+------------------+------------------+----------------+--------+----------+-------------------+--------------------+--------------------+--------------------+-------------------+--------------------+
only showing top 10 rows
[2025-10-06T14:05:43.897+0000] {logging_mixin.py:188} INFO - Количество строк загруженных из файла 507914
[2025-10-06T14:05:43.899+0000] {logging_mixin.py:188} INFO - root
 |-- house_id: integer (nullable = true)
 |-- latitude: double (nullable = true)
 |-- longitude: double (nullable = true)
 |-- maintenance_year: string (nullable = true)
 |-- square: string (nullable = true)
 |-- population: string (nullable = true)
 |-- region: string (nullable = true)
 |-- locality_name: string (nullable = true)
 |-- address: string (nullable = true)
 |-- full_address: string (nullable = true)
 |-- communal_service_id: string (nullable = true)
 |-- description: string (nullable = true)
[2025-10-06T14:05:43.951+0000] {logging_mixin.py:188} INFO - root
 |-- house_id: integer (nullable = true)
 |-- latitude: float (nullable = true)
 |-- longitude: float (nullable = true)
 |-- maintenance_year: integer (nullable = true)
 |-- square: float (nullable = true)
 |-- population: integer (nullable = true)
 |-- region: string (nullable = true)
 |-- locality_name: string (nullable = true)
 |-- address: string (nullable = true)
 |-- full_address: string (nullable = true)
 |-- communal_service_id: integer (nullable = true)
 |-- description: string (nullable = true)
[2025-10-06T14:05:43.962+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-06T14:05:43.962+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main.py", line 87, in run_spark_job
    .withColumn("year_tmp", col("maintenance_year")[:2] + lit("0")) \
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/column.py", line 705, in __getitem__
    return self.substr(k.start, k.stop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/column.py", line 909, in substr
    raise PySparkTypeError(
pyspark.errors.exceptions.base.PySparkTypeError: [NOT_SAME_TYPE] Argument `startPos` and `length` should be the same type, got NoneType and int.
[2025-10-06T14:05:43.970+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=main, task_id=run_pyspark_task, run_id=manual__2025-10-06T14:05:22.989839+00:00, execution_date=20251006T140522, start_date=20251006T140524, end_date=20251006T140543
[2025-10-06T14:05:43.982+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 147 for task run_pyspark_task ([NOT_SAME_TYPE] Argument `startPos` and `length` should be the same type, got NoneType and int.; 6705)
[2025-10-06T14:05:43.997+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-06T14:05:44.011+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-06T14:05:44.014+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
