[2025-10-02T14:39:23.688+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-02T14:39:23.705+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main.run_write_postgres manual__2025-10-02T14:39:15.240671+00:00 [queued]>
[2025-10-02T14:39:23.711+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main.run_write_postgres manual__2025-10-02T14:39:15.240671+00:00 [queued]>
[2025-10-02T14:39:23.711+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-02T14:39:23.722+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_write_postgres> on 2025-10-02 14:39:15.240671+00:00
[2025-10-02T14:39:23.729+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=15628) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-02T14:39:23.731+0000] {standard_task_runner.py:63} INFO - Started process 15630 to run task
[2025-10-02T14:39:23.731+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'main', 'run_write_postgres', 'manual__2025-10-02T14:39:15.240671+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmppxi5n1lh']
[2025-10-02T14:39:23.733+0000] {standard_task_runner.py:91} INFO - Job 126: Subtask run_write_postgres
[2025-10-02T14:39:23.769+0000] {task_command.py:426} INFO - Running <TaskInstance: main.run_write_postgres manual__2025-10-02T14:39:15.240671+00:00 [running]> on host 5adecdfd8c83
[2025-10-02T14:39:23.837+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main' AIRFLOW_CTX_TASK_ID='run_write_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T14:39:15.240671+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-02T14:39:15.240671+00:00'
[2025-10-02T14:39:23.839+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-02T14:39:26.269+0000] {logging_mixin.py:188} INFO - Получен валидный DataFrame
[2025-10-02T14:39:26.275+0000] {logging_mixin.py:188} INFO -    column1 column2
0        1     cat
[2025-10-02T14:39:26.275+0000] {logging_mixin.py:188} INFO - Размер: (1, 2)
[2025-10-02T14:39:26.275+0000] {logging_mixin.py:188} INFO - Вот сам DataFrame
[2025-10-02T14:39:26.277+0000] {logging_mixin.py:188} INFO -    column1 column2
0        1     cat
[2025-10-02T14:39:26.655+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-02T14:39:26.657+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-02T14:39:26.671+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=main, task_id=run_write_postgres, run_id=manual__2025-10-02T14:39:15.240671+00:00, execution_date=20251002T143915, start_date=20251002T143923, end_date=20251002T143926
[2025-10-02T14:39:26.717+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-02T14:39:26.731+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-02T14:39:26.735+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
