[2025-10-02T14:41:29.939+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-02T14:41:29.958+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main.run_write_postgres manual__2025-10-02T14:41:22.386705+00:00 [queued]>
[2025-10-02T14:41:29.966+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main.run_write_postgres manual__2025-10-02T14:41:22.386705+00:00 [queued]>
[2025-10-02T14:41:29.967+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-02T14:41:29.990+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_write_postgres> on 2025-10-02 14:41:22.386705+00:00
[2025-10-02T14:41:29.998+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=16008) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-02T14:41:30.000+0000] {standard_task_runner.py:63} INFO - Started process 16010 to run task
[2025-10-02T14:41:30.000+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'main', 'run_write_postgres', 'manual__2025-10-02T14:41:22.386705+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp47t0p1qw']
[2025-10-02T14:41:30.003+0000] {standard_task_runner.py:91} INFO - Job 128: Subtask run_write_postgres
[2025-10-02T14:41:30.043+0000] {task_command.py:426} INFO - Running <TaskInstance: main.run_write_postgres manual__2025-10-02T14:41:22.386705+00:00 [running]> on host 5adecdfd8c83
[2025-10-02T14:41:30.111+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main' AIRFLOW_CTX_TASK_ID='run_write_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T14:41:22.386705+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-02T14:41:22.386705+00:00'
[2025-10-02T14:41:30.112+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-02T14:41:32.797+0000] {logging_mixin.py:188} INFO - Получен валидный DataFrame
[2025-10-02T14:41:32.803+0000] {logging_mixin.py:188} INFO -    column1 column2
0        1     cat
[2025-10-02T14:41:32.805+0000] {logging_mixin.py:188} INFO - Размер: (1, 2)
[2025-10-02T14:41:32.805+0000] {logging_mixin.py:188} INFO - Вот сам DataFrame
[2025-10-02T14:41:32.808+0000] {logging_mixin.py:188} INFO -    column1 column2
0        1     cat
[2025-10-02T14:41:33.172+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-02T14:41:33.174+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-02T14:41:33.184+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=main, task_id=run_write_postgres, run_id=manual__2025-10-02T14:41:22.386705+00:00, execution_date=20251002T144122, start_date=20251002T144129, end_date=20251002T144133
[2025-10-02T14:41:33.227+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-02T14:41:33.242+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-02T14:41:33.246+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
